version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./frontend/build:/app/static
    environment:
      - FLASK_ENV=development