"""Add steps to Message model

Revision ID: 1fe15c541143
Revises: 4e6881ce14e9
Create Date: 2024-09-04 05:49:08.908027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fe15c541143'
down_revision = '4e6881ce14e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('steps', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'steps')
    # ### end Alembic commands ###
